[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "EEJ9MWyxnVHvq7WL4GQ8NBrqpX3cUUP2tb77cmyQa5ui"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-initialize="yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.test.ts"
test-deposit="yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deposit.test.ts"
test-withdraw="yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw.test.ts"
